#pragma once

#define BOOTMAGIC_KEY_SALT KC_LSFT
#define BOOTMAGIC_KEY_DEFAULT_LAYER_0 KC_Q
#define BOOTMAGIC_KEY_DEFAULT_LAYER_1 KC_W
#define BOOTMAGIC_KEY_DEFAULT_LAYER_2 KC_E

#define AUTO_SHIFT_TIMEOUT 130
#define NO_AUTO_SHIFT_SPECIAL
#define NO_AUTO_SHIFT_NUMERIC
